name: Push minimal template docker image to dockerhub

on:
  workflow_run:
    workflows:
      - "Run tests"
    branches:
      - main
    types:
      - completed

jobs:
  push_image_to_dockerhub:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        env:
          cookiecutter_project_name: "{{cookiecutter_project_name}}"
        with:
          file: Dockerfile
          context: ./${{cookiecutter_project_name}}/template_minimal
          push: true
          tags: rafsaf/minimal-fastapi-postgres-template:latest
