name: Manual push minimal template docker image to dockerhub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "stable"

jobs:
  manual_push_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: copy minimal template to root folder
        run: |
          cp -r \{\{cookiecutter.project_name\}\}/template_minimal/ .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: ./template_minimal
          push: true
          tags: rafsaf/minimal-fastapi-postgres-template:${{ github.event.inputs.tag }}
